### ISSUE TITLE
Failed to build if IOS_ARCH="arm64;x86_64"

### ISSUE THREAD

**Issue by Junch** [wang-bin/ios.cmake#1]
I replaced the ios.cmake with the old one in cristeab/ios-cmake and run the test.

➜  build git:(master) ✗ cmake .. -DCMAKE_TOOLCHAIN_FILE=../../../toolchain/ios.cmake -DIOS_ARCH="arm64;x86_64"
-- Building with Xcode version: 8.3.2
iOS universal
-- Configuring iOS build for platform: iphoneos, architecture(s): arm64;x86_64
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Building for minimum iOS version: 10.3 (SDK version: 10.3)
IOS_EMBEDDED_FRAMEWORK: 0
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk for platform: iphoneos arm64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk for platform: iphonesimulator x86_64
CMAKE_OSX_ARCHITECTURES: arm64;x86_64
-- Building with Xcode version: 8.3.2
-- Configuring iOS build for platform: iphoneos, architecture(s): arm64;x86_64
-- Building for minimum iOS version: 10.3 (SDK version: 10.3)
IOS_EMBEDDED_FRAMEWORK: 0
CMAKE_OSX_ARCHITECTURES: arm64;x86_64
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/juchen3/Github/ios-cmake/samples/hello-lib/build
➜  build git:(master) ✗ make
Scanning dependencies of target hello-lib
[ 33%] Building CXX object CMakeFiles/hello-lib.dir/HelloWorld.cpp.o
clang: error: no such file or directory: 'arm64'
clang: warning: no such sysroot directory: '-arch' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '-arch' [-Wmissing-sysroot]
make[2]: *** [CMakeFiles/hello-lib.dir/HelloWorld.cpp.o] Error 1
make[1]: *** [CMakeFiles/hello-lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by wang-bin** [comment]
What's your cmake version?
